#
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.3.1'
config-version: 2

quoting:
  database: false
  schema: false
  identifier: false

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

snapshots:
  +post-hook: 
    - "update {{ this }} set current_indicator = case when dbt_valid_to is not null then 'N' else 'Y' end"
  +target_database: "{{ 'prd_p_edw' if target.name == 'prod' else 'dev_p_edw' }}"
  +target_schema: "dbt_rrajan_snapshots"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  jaffle_shop:
    marts:
      +schema: marts
      core:
        +materialized: table
    staging:
      +schema: staging
      +materialized: view
    dbt_artifacts:
      +schema: dbt_rrajan_artifacts

on-run-end: 
  "{{ dbt_artifacts.upload_results(results) }}"