version: 2
 
groups:
  - name: customer_group
    owner:
      name: RR_JF
      email: rijesh.rajan@dbtlabs.com
      
models:
  - name: dim_customers
    group: customer_group
    access: public

  - name: fct_orders
    group: customer_group
    access: private

  - name: int_orders__pivoted
    group: customer_group
    access: protected

  - name: customer_order_unique
    group: customer_group
    access: public
