version: 2

groups:
  - name: customer_group
    owner:
      name: RR_JF
      email: rijesh.rajan@dbtlabs.com
      
models:
  - name: dim_customers
    access: public
    config:
      contract:
        enforced: true
    columns:
      - name: customer_id
        data_type: int
        constraints:
          - type: not_null
      - name: first_name
        data_type: string
      - name: last_name
        data_type: string
      - name: '"customer name"'
        data_type: string
      - name: first_order_date  
        data_type: date
      - name: lifetime_value 
        data_type: int
      - name: most_recent_order_date
        data_type: date
      - name: number_of_orders
        data_type: int
  - name: fct_orders
    access: private
  - name: int_orders__pivoted
    access: protected