# First, define the group and owner
groups:
  - name: customer_success
    owner:
      name: Customer Success Team
      email: rijesh.rajan@dbtlabs.com

# Then, add 'group' + 'access' modifier to specific models
models:
  # This is a public model -- it's a stable & mature interface for other teams/projects
  - name: dim_customers
    group: customer_success
    access: public
    
  # This is a private model -- it's an intermediate transformation intended for use in this context *only*
  - name: fct_orders
    group: customer_success
    access: private
    
  # This is a protected model -- it might be useful elsewhere in *this* project,
  # but it shouldn't be exposed elsewhere
  - name: int_orders__pivoted
    group: customer_success
    access: protected

  - name: customer_order_unique 
    group: customer_success
    access: public