version: 2

groups:
  - name: customer_group
    owner:
      name: RR_JF
      email: rijesh.rajan@dbtlabs.com
      
models:
  - name: dim_customers
    access: public
    config:
      group: customer_group
  - name: fct_orders
    access: private
    config:
      group: customer_group
  - name: int_orders__pivoted
    access: protected
    config:
      group: customer_group
  - name: customer_order_unique
    access: public
    config:
      group: customer_group